### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/backnet#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Shivansh2407** [comment]
Can You explain on this more....I would like to work on this ...Please assign me this issue

**Comment by kaiiyer** [comment]
@Shivansh2407 Thanks for your interest in the project.
Fork the repo and run the app. If you think something should be improved(UI, Dependencies, Code) or if you come across any bug, then you can modify the app and open a pull request.

**Comment by kaiiyer** [comment]
Thanks for the contributions during Hacktoberfest !!!
